# -*- mode: ruby -*-

servers=[
  {
    :hostname => "mongo-master",
    :ip => "192.168.50.50",
    :box => "romanow/ansible-box",
    :ram => 1024,
    :cpu => 1
  },
  {
    :hostname => "mongo-slave",
    :ip => "192.168.50.51",
    :box => "romanow/ansible-box",
    :ram => 1024,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
  config.ssh.username = "ansible"
  config.ssh.password = "root"

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]

      config.vm.provider "virtualbox" do |vm|
        vm.memory = machine[:ram]
        vm.cpus = machine[:cpu]
      end
    end

    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/ansible/.ssh/authorized_keys
      SHELL
    end
  end
end